build: false

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      APPVEYOR_YML_DISABLE_PS_LINUX: true
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS
      APPVEYOR_YML_DISABLE_PS_LINUX: true

stack: python 3.8

install: |
  if [[ "${APPVEYOR_BUILD_WORKER_IMAGE}" == "Ubuntu" ]]; then
      sudo apt install -y graphviz graphviz-dev
  elif [[ "${APPVEYOR_BUILD_WORKER_IMAGE}" == "macOS" ]]; then
      brew install -y graphviz
  fi
  pip install --upgrade pip
  pip install -r requirements.txt
  pip install -r requirements_test.txt
  pip install -r requirements_doc.txt
  pip install .

test_script:
  - mkdir for_test
  - cd for_test
  - pytest -v --cov=skdag --pyargs skdag

after_test:
  - cp .coverage ${APPVEYOR_BUILD_FOLDER}
  - cd ${APPVEYOR_BUILD_FOLDER}
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov
