build: false

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      APPVEYOR_YML_DISABLE_PS_LINUX: true

stack: python 3.8

install: |
  if [[ "${APPVEYOR_BUILD_WORKER_IMAGE}" == "Ubuntu" ]]; then
    sudo apt update
    sudo apt install -y graphviz libgraphviz-dev
  elif [[ "${APPVEYOR_BUILD_WORKER_IMAGE}" == "macOS" ]]; then
    brew update
    brew install graphviz
  fi
  pip install --upgrade pip
  for f in $(find . -maxdepth 1 -name 'requirements*.txt'); do
    pip install -r ${f}
  done
  pip install pandas  # Needed for some estimator checks.
  pip install .

test_script:
  - mkdir for_test
  - cd for_test
  - pytest -v --cov=skdag --pyargs skdag

after_test:
  - cp .coverage ${APPVEYOR_BUILD_FOLDER}
  - cd ${APPVEYOR_BUILD_FOLDER}
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov
